### ISSUE TITLE
Having issues connecting to Mongodb

### ISSUE THREAD

**Issue by Miguel-Moretti** [Tom-Beijner/Mordhau-RCON#8]
Hi, hopefully you could help me with connecting to the Mongodb database that I've created?
The link I get provided to connect to my mongodb database is: 
mongodb+srv://MiguelMoretti:<password>@doa.fi4sd.mongodb.net/myFirstDatabase?retryWrites=true&w=majority

Any help with properly converting this link into the "host" and "database" fields within my config.json file, would be greatly appreciated!

**Comment by Tom-Beijner** [comment]
From that connection string it would be like this;
host: doa.fi4sd.mongodb.net
database: *can by anything like I use `data`*

JSON format:
```json
"host": "doa.fi4sd.mongodb.net",
"database": "data"
```
